# ==============================================================================
# Omarchy Dynamic Theme Configuration for Qutebrowser
# Automatically generated by Omarchy Theme Engine
# ==============================================================================
# Theme mode: {{ mode }}
# Primary background: {{ background }}
# Accent: {{ accent }}
# ==============================================================================

BG = "{{ background }}"
BG_RGB = "{{ background_rgb }}"
DARK_BG = "{{ dark_background }}"
DARK_BG_RGB = "{{ dark_background_rgb }}"
DARKER_BG = "{{ darker_background }}"
DARKER_BG_RGB = "{{ darker_background_rgb }}"
LIGHTER_BG = "{{ lighter_background }}"
LIGHTER_BG_RGB = "{{ lighter_background_rgb }}"

FG = "{{ foreground }}"
ACCENT = "{{ accent }}"
MUTED = "{{ muted }}"
SELECTION_BG = "{{ selection_background }}"
SELECTION_FG = "{{ selection_foreground }}"

RED = "{{ red }}"
RED_RGB = "{{ red_rgb }}"
GREEN = "{{ green }}"
GREEN_RGB = "{{ green_rgb }}"
YELLOW = "{{ yellow }}"
YELLOW_RGB = "{{ yellow_rgb }}"
BLUE = "{{ blue }}"
BLUE_RGB = "{{ blue_rgb }}"
MAGENTA = "{{ magenta }}"
MAGENTA_RGB = "{{ magenta_rgb }}"
CYAN = "{{ cyan }}"

MODE = "{{ mode }}"

# ------------------------------------------------------------------------------
# Window & Webpage Transparency
# ------------------------------------------------------------------------------
c.window.transparent = True

# Webpage background (theme background; compositor handles window opacity/blur)
c.colors.webpage.bg = BG
c.colors.webpage.preferred_color_scheme = MODE
c.colors.webpage.darkmode.enabled = (MODE == "dark")

# ------------------------------------------------------------------------------
# Tab Bar Colors (Translucent & Minimal)
# ------------------------------------------------------------------------------
# Tab bar overall background
c.colors.tabs.bar.bg = f"rgba({DARKER_BG_RGB}, 0.75)"

# Unselected tabs
c.colors.tabs.even.bg = f"rgba({DARK_BG_RGB}, 0.65)"
c.colors.tabs.even.fg = MUTED
c.colors.tabs.odd.bg = f"rgba({DARKER_BG_RGB}, 0.65)"
c.colors.tabs.odd.fg = MUTED

# Selected tabs (active)
c.colors.tabs.selected.even.bg = f"rgba({BG_RGB}, 0.95)"
c.colors.tabs.selected.even.fg = ACCENT
c.colors.tabs.selected.odd.bg = f"rgba({BG_RGB}, 0.95)"
c.colors.tabs.selected.odd.fg = ACCENT

# Pinned tabs
c.colors.tabs.pinned.even.bg = f"rgba({DARK_BG_RGB}, 0.65)"
c.colors.tabs.pinned.even.fg = MUTED
c.colors.tabs.pinned.odd.bg = f"rgba({DARKER_BG_RGB}, 0.65)"
c.colors.tabs.pinned.odd.fg = MUTED
c.colors.tabs.pinned.selected.even.bg = f"rgba({BG_RGB}, 0.95)"
c.colors.tabs.pinned.selected.even.fg = ACCENT
c.colors.tabs.pinned.selected.odd.bg = f"rgba({BG_RGB}, 0.95)"
c.colors.tabs.pinned.selected.odd.fg = ACCENT

# Tab indicators
c.colors.tabs.indicator.start = BLUE
c.colors.tabs.indicator.stop = GREEN
c.colors.tabs.indicator.error = RED
c.colors.tabs.indicator.system = "none"

# ------------------------------------------------------------------------------
# Statusbar Colors
# ------------------------------------------------------------------------------
# Normal mode
c.colors.statusbar.normal.bg = f"rgba({BG_RGB}, 0.85)"
c.colors.statusbar.normal.fg = FG

# Insert mode
c.colors.statusbar.insert.bg = f"rgba({GREEN_RGB}, 0.90)"
c.colors.statusbar.insert.fg = DARKER_BG

# Passthrough mode
c.colors.statusbar.passthrough.bg = f"rgba({BLUE_RGB}, 0.90)"
c.colors.statusbar.passthrough.fg = DARKER_BG

# Command prompt mode
c.colors.statusbar.command.bg = f"rgba({DARKER_BG_RGB}, 0.92)"
c.colors.statusbar.command.fg = FG
c.colors.statusbar.command.private.bg = f"rgba({DARKER_BG_RGB}, 0.92)"
c.colors.statusbar.command.private.fg = YELLOW

# Private browsing
c.colors.statusbar.private.bg = f"rgba({DARKER_BG_RGB}, 0.90)"
c.colors.statusbar.private.fg = MUTED

# Caret mode
c.colors.statusbar.caret.bg = f"rgba({MAGENTA_RGB}, 0.90)"
c.colors.statusbar.caret.fg = DARKER_BG
c.colors.statusbar.caret.selection.bg = SELECTION_BG
c.colors.statusbar.caret.selection.fg = SELECTION_FG

# Progress bar in statusbar
c.colors.statusbar.progress.bg = ACCENT

# URL display colors in statusbar
c.colors.statusbar.url.fg = FG
c.colors.statusbar.url.hover.fg = CYAN
c.colors.statusbar.url.success.http.fg = YELLOW
c.colors.statusbar.url.success.https.fg = GREEN
c.colors.statusbar.url.warn.fg = YELLOW
c.colors.statusbar.url.error.fg = RED

# ------------------------------------------------------------------------------
# Completion Menu (Omnibar)
# ------------------------------------------------------------------------------
c.colors.completion.category.bg = f"rgba({DARK_BG_RGB}, 0.95)"
c.colors.completion.category.fg = ACCENT
c.colors.completion.category.border.top = f"rgba({DARK_BG_RGB}, 0.95)"
c.colors.completion.category.border.bottom = f"rgba({DARK_BG_RGB}, 0.95)"

c.colors.completion.even.bg = f"rgba({BG_RGB}, 0.88)"
c.colors.completion.odd.bg = f"rgba({DARKER_BG_RGB}, 0.88)"
c.colors.completion.fg = FG

c.colors.completion.item.selected.bg = SELECTION_BG
c.colors.completion.item.selected.fg = SELECTION_FG
c.colors.completion.item.selected.border.top = SELECTION_BG
c.colors.completion.item.selected.border.bottom = SELECTION_BG
c.colors.completion.item.selected.match.fg = ACCENT

c.colors.completion.match.fg = ACCENT
c.colors.completion.scrollbar.bg = f"rgba({DARKER_BG_RGB}, 0.88)"
c.colors.completion.scrollbar.fg = MUTED

# ------------------------------------------------------------------------------
# Context Menu
# ------------------------------------------------------------------------------
c.colors.contextmenu.menu.bg = f"rgba({BG_RGB}, 0.95)"
c.colors.contextmenu.menu.fg = FG
c.colors.contextmenu.selected.bg = SELECTION_BG
c.colors.contextmenu.selected.fg = SELECTION_FG
c.colors.contextmenu.disabled.bg = f"rgba({DARK_BG_RGB}, 0.95)"
c.colors.contextmenu.disabled.fg = MUTED

# ------------------------------------------------------------------------------
# Downloads Bar
# ------------------------------------------------------------------------------
c.colors.downloads.bar.bg = f"rgba({DARK_BG_RGB}, 0.90)"
c.colors.downloads.start.bg = BLUE
c.colors.downloads.start.fg = DARKER_BG
c.colors.downloads.stop.bg = GREEN
c.colors.downloads.stop.fg = DARKER_BG
c.colors.downloads.error.bg = RED
c.colors.downloads.error.fg = FG

# ------------------------------------------------------------------------------
# Hints & Keyhints
# ------------------------------------------------------------------------------
c.colors.hints.bg = ACCENT
c.colors.hints.fg = DARKER_BG
c.colors.hints.match.fg = GREEN

c.colors.keyhint.bg = f"rgba({BG_RGB}, 0.92)"
c.colors.keyhint.fg = FG
c.colors.keyhint.suffix.fg = YELLOW

# ------------------------------------------------------------------------------
# Messages (Notification popups)
# ------------------------------------------------------------------------------
c.colors.messages.error.bg = RED
c.colors.messages.error.border = RED
c.colors.messages.error.fg = DARKER_BG

c.colors.messages.warning.bg = YELLOW
c.colors.messages.warning.border = YELLOW
c.colors.messages.warning.fg = DARKER_BG

c.colors.messages.info.bg = f"rgba({DARK_BG_RGB}, 0.92)"
c.colors.messages.info.border = f"rgba({DARK_BG_RGB}, 0.92)"
c.colors.messages.info.fg = FG

# ------------------------------------------------------------------------------
# Prompts
# ------------------------------------------------------------------------------
c.colors.prompts.bg = f"rgba({BG_RGB}, 0.92)"
c.colors.prompts.border = f"rgba({DARK_BG_RGB}, 0.92)"
c.colors.prompts.fg = FG
c.colors.prompts.selected.bg = SELECTION_BG
c.colors.prompts.selected.fg = SELECTION_FG
